slst-rota/app/modules/student/models.py
from calendar import day_name  # Days
from datetime import timedelta, datetime, date  # Times
from typing import Union, Callable, List, Tuple  # Typing

from flask import escape  # Escape

from app import db, BaseModel, Utils  # DB


# Define a Session model
class Session(BaseModel):
    __tablename__ = 'sessions'

    id = db.Column(db.Integer, primary_key=True)
    day = db.Column(db.Integer, nullable=False)
    start_time = db.Column(db.Integer, nullable=False)
    end_time = db.Column(db.Integer, nullable=False)
    archived = db.Column(db.SmallInteger, nullable=False, default=0)

    assignments = db.relationship('Assignment')
    unavailabilities = db.relationship('Unavailability')

    # New instance instantiation procedure
    def __init__(self, day: int, start_time: int, end_time: int):
        self.day = day
        self.start_time = start_time
        self.end_time = end_time

    @property
    def day_frmt(self):
        return list(day_name)[self.day]  # day name

    @property
    def start_time_frmt(self):
        dt = Utils.minutes_today(self.start_time)
        return dt.strftime("%H:%M")

    @property
    def end_time_frmt(self):
        dt = Utils.minutes_today(self.end_time)
        return dt.strftime("%H:%M")

    @property
    def start_time_time(self):
        dt = Utils.minutes_today(self.start_time)
        return dt.time()

    @property
    def end_time_time(self):
        dt = Utils.minutes_today(self.end_time)
        return dt.time()


# Define an Assignment model
class Assignment(BaseModel):
    __tablename__ = 'assignments'

    user_id = db.Column(
        db.Integer,
        db.ForeignKey('users.id', ondelete='CASCADE'),
        primary_key=True,
        nullable=False,
    )
    user = db.relationship('User')

    session_id = db.Column(
        db.Integer,
        db.ForeignKey('sessions.id', ondelete='CASCADE'),
        primary_key=True,
        nullable=False,
    )
    session = db.relationship('Session')

    created = db.Column(db.DateTime, primary_key=True, nullable=False)
    removed = db.Column(db.DateTime, nullable=True)

    # New instance instantiation procedure
    def __init__(self, user_id: int, session_id: int, created: datetime = None):
        self.user_id = user_id
        self.session_id = session_id
        self.created = created or datetime.now()

    @property
    def attendance(self) -> List[Tuple[date, Union['Attendance', None]]]:
        results = []
        delta = (self.removed.date() if self.removed else datetime.now().date()) - self.created.date()

        for i in range(delta.days + 1):
            # Day assignment created, if assignment created after session start, ignore
            if i == 0:
                if Utils.minutes_datetime(self.created) >= self.session.start_time:
                    continue

            d = self.created.date() + timedelta(days=i)

            data = Attendance.query.filter_by(user_id=self.user_id, session_id=self.session_id, date=d).first()

            # If has not happened yet
            if d == datetime.now().date():
                if self.session.start_time >= Utils.minutes_now() or (
                        Utils.minutes_now() <= self.session.end_time and (not data or (data and not data.out_time))):
                    continue

            results.append((d, data))

        return results


# Convert sessions to the view needed for the rota
def session_to_rota_view(session: Session, highlight_check: Union[Callable, None] = None) -> List[list]:
    data = [False, []]
    data[1].append(session.start_time_frmt)  # Get hours:minutes
    data[1].append(session.end_time_frmt)  # Get hours:minutes

    # Usernames
    data[1].append([])
    for assignment in session.assignments:
        if assignment.removed or assignment.user.disabled:
            continue
        data[1][-1].append(assignment.user.username)
        # Highlight
        if highlight_check is not None and highlight_check(assignment):
            data[0] = True
    data[1][-1] = ", ".join(data[1][-1]) or "<i>None</i>"

    return data


# Define an Unavailability model
class Unavailability(BaseModel):
    __tablename__ = 'unavailabilities'

    user_id = db.Column(
        db.Integer,
        db.ForeignKey('users.id', ondelete='CASCADE'),
        primary_key=True,
        nullable=False,
    )
    user = db.relationship('User')

    session_id = db.Column(
        db.Integer,
        db.ForeignKey('sessions.id', ondelete='CASCADE'),
        primary_key=True,
        nullable=False,
    )
    session = db.relationship('Session')

    reason = db.Column(db.String, nullable=False)

    # New instance instantiation procedure
    def __init__(self, user_id: int, session_id: int, reason: str):
        self.user_id = user_id
        self.session_id = session_id
        self.reason = reason

    @property
    def reason_clean(self) -> str:
        return escape(self.reason)


# Define an Attendance model
class Attendance(BaseModel):
    __tablename__ = 'attendance'

    id = db.Column(db.Integer, primary_key=True)

    user_id = db.Column(
        db.Integer,
        db.ForeignKey('users.id', ondelete='CASCADE'),
        nullable=False,
    )
    user = db.relationship('User')

    session_id = db.Column(
        db.Integer,
        db.ForeignKey('sessions.id', ondelete='CASCADE'),
        nullable=False,
    )
    session = db.relationship('Session')

    date = db.Column(db.Date, nullable=False)
    in_time = db.Column(db.DateTime, nullable=False)
    in_time_org = db.Column(db.DateTime, nullable=False)
    out_time = db.Column(db.DateTime, nullable=True, default=None)
    out_time_org = db.Column(db.DateTime, nullable=False)

    # New instance instantiation procedure
    def __init__(self, user_id: int, session_id: int, in_time_org: datetime, out_time_org: datetime, date: date = None,
                 in_time: datetime = None, out_time: datetime = None):
        self.user_id = user_id
        self.session_id = session_id
        self.date = date or datetime.now().date()
        self.in_time = in_time or datetime.now()
        self.in_time_org = in_time_org
        self.out_time = out_time
        self.out_time_org = out_time_org

    # New instance from a session instance to make things easier
    @classmethod
    def from_session(cls, user_id: int, session: Session) -> 'Attendance':
        return cls(user_id, session.id, Utils.minutes_today(session.start_time), Utils.minutes_today(session.end_time))

    @property
    def in_diff(self) -> float:
        # Minutes
        return (self.in_time - self.in_time_org).total_seconds() / 60

    @property
    def out_diff(self) -> float:
        # Minutes
        return ((self.out_time or self.out_time_org) - self.out_time_org).total_seconds() / 60

    @property
    def current(self) -> bool:
        if self.in_time_org < datetime.now() < self.out_time_org and not self.out_time:
            return True
        return False

slst-rota/app/modules/student/forms.py
from flask_wtf import FlaskForm  # Form
from wtforms import StringField, BooleanField  # Form: Elements


# Unavailability (using WTForms)
class UnavailabilityForm(FlaskForm):
    unavailable = BooleanField('Unavailable')
    reason = StringField('Reason')

slst-rota/app/modules/student/__init__.py
from .controllers import *
from .models import *

slst-rota/app/modules/student/controllers.py
import calendar  # Calendar
from datetime import datetime  # Datetime
from typing import Tuple, Union  # Typing

from flask import Blueprint, request, render_template, flash, redirect, url_for  # Flask

from app import db_session, error_render, Utils  # DB, Errors
from app.modules import auth  # Auth
from app.modules.auth import User  # User
from app.modules.student.forms import UnavailabilityForm  # Form
from app.modules.student.models import Session, session_to_rota_view, Assignment, Unavailability, \
    Attendance  # Rota Sessions

# Blueprint
__a = [
    Session, Assignment, Unavailability, Attendance
]  # Convince pycharm things are used (and stop warnings)
student = Blueprint('student', __name__, url_prefix='/student')


# Standard check for all routes
def auth_check():
    user = auth.current_user()
    error = None

    # If no session exists
    if not error and not user:
        error = redirect(url_for('auth.login'))

    # If not student
    if not error and user.auth_level != 1:
        error = error_render("Student access only",
                             "This page is only accessible to users with the student authentication level")

    return user, error


# Quick method to get next/current assignment
def next_current_assignment(user: User) -> Tuple[Union[Session, None], bool, bool]:
    # Get session assignments
    data = Session.query.filter_by(archived=False).order_by(Session.day.asc(), Session.start_time.asc()).all()
    data = [f for f in data if user.id in [g.user.id for g in f.assignments if not g.removed]]

    # Handle no assignments
    if not data:
        return None, False

    # Get next/current
    next_session = data[0]
    for session in data:
        # Session can't be before now (day)
        if session.day < datetime.today().weekday():
            continue

        # Assignment can't be before now (end time)
        if session.end_time < Utils.minutes_now():
            continue

        next_session = session
        break

    # Check if the next session is current
    session_is_current = False
    if next_session.day == datetime.today().weekday() \
            and next_session.start_time <= Utils.minutes_now() \
            and next_session.end_time >= Utils.minutes_now():
        session_is_current = True

    # Check if the next session is soon
    session_is_soon = False
    if not session_is_current \
            and next_session.day == datetime.today().weekday() \
            and next_session.start_time - 5 <= Utils.minutes_now():
        session_is_soon = True

    return next_session, session_is_current, session_is_soon


# Quick method to get if a user is signed in/out for a session
def signed_in_out_session(user: User, session: Union[Session, None]) -> Tuple[Union[Attendance, None], bool, bool]:
    if not session:
        return None, False, False

    data = Attendance.query.filter_by(user_id=user.id, session_id=session.id).order_by(
        Attendance.in_time.desc()).first()

    # No attendance or not today's attendance
    if not data or data.in_time.date() != datetime.now().date():
        return data, False, False

    # If has an out time
    if data.out_time:
        return data, True, True

    # In but not out
    return data, True, False


# Home
@student.route('/', methods=['GET'])
def home():
    user, error = auth_check()
    if error:
        return error

    # Get next session for student
    next_session, session_is_current, session_is_soon = next_current_assignment(user)

    # Format for table macro
    next_session_org = next_session
    if next_session:
        next_session = [
            session_is_current,
            [
                next_session.day_frmt,
                next_session.start_time_frmt,
                next_session.end_time_frmt,
                ", ".join([f.user.username for f in next_session.assignments if not f.removed])
            ]
        ]

    # Get unavailability
    data = Session.query.filter_by(archived=False).all()
    data2 = [f for f in Unavailability.query.filter_by(user_id=user.id).all() if not f.session.archived]
    unavailability_stat = "Unavailable {} / {} sessions.<br/>({:.2f}% availability)".format(
        len(data2), len(data), (1 - (len(data2) / len(data))) * 100)

    return render_template("student/index.jinja2", session_is_current=session_is_current,
                           session_is_soon=session_is_soon, next_session=next_session,
                           unavailability_stat=unavailability_stat,
                           signed_in_out_session=signed_in_out_session(user, next_session_org))


# Rota
@student.route('/rota/', methods=['GET'])
def rota():
    user, error = auth_check()
    if error:
        return error

    # Get rota data
    data = Session.query.filter_by(archived=False).order_by(Session.day.asc(), Session.start_time.asc()).all()
    rota_data = []
    current_day = None
    for session in data:
        # Only current user
        if user.id not in [f.user.id for f in session.assignments if not f.removed]:
            continue

        # Day subheadings
        if session.day != current_day:
            rota_data.append([False, [list(calendar.day_name)[session.day], "", ""], True])
            current_day = session.day

        # Assignments for day
        rota_data.append(session_to_rota_view(session, lambda a: a.session.day == datetime.today().weekday()))

    return render_template("student/rota.jinja2", title="Rota view for {}".format(user.username),
                           rota_data=rota_data, show_rota_full=True,
                           has_highlighted=bool(sum([f[0] for f in rota_data])))


# Full Rota
@student.route('/rota/full/', methods=['GET'])
def rota_full():
    user, error = auth_check()
    if error:
        return error

    # Get rota data
    data = Session.query.filter_by(archived=False).order_by(Session.day.asc(), Session.start_time.asc()).all()
    rota_data = []
    current_day = None
    for session in data:
        # Day subheadings
        if session.day != current_day:
            rota_data.append([False, [list(calendar.day_name)[session.day], "", ""], True])
            current_day = session.day

        # Assignments for day (highlight ones with current user)
        rota_data.append(session_to_rota_view(session, lambda a: a.user.id == user.id))

    return render_template("student/rota.jinja2", title="Full rota view",
                           rota_data=rota_data, show_rota_full=False,
                           has_highlighted=bool(sum([f[0] for f in rota_data])))


# Unavailability
@student.route('/unavailability/', methods=['GET'])
def unavailability():
    user, error = auth_check()
    if error:
        return error

    # Get rota data
    data = Session.query.filter_by(archived=False).order_by(Session.day.asc(), Session.start_time.asc()).all()
    rota_data = []
    current_day = None
    for session in data:

        # Don't show assigned sessions
        assigned = False
        if user.id in [f.user.id for f in session.assignments if not f.removed]:
            assigned = True

        # Day subheadings
        if session.day != current_day:
            rota_data.append([False, [list(calendar.day_name)[session.day], "", "", ""], True])
            current_day = session.day

        # Sessions
        unavailable = user.id in [f.user.id for f in session.unavailabilities]
        rota_data.append([
            unavailable,
            [
                session.start_time_frmt,
                session.end_time_frmt,
                "Yes" if unavailable else "No",
                "Currently assigned, unable to update." if assigned else
                '<a class="button primary mbt-0" href="{}"><i class="fas fa-lg fa-edit"></i> Update unavailability</a>'
                ''.format(url_for('student.unavailability_edit', id=session.id))
            ]
        ])

    return render_template("student/unavailability.jinja2", rota_data=rota_data)


# Unavailability
@student.route('/unavailability/edit/<int:id>', methods=['GET', 'POST'])
def unavailability_edit(id: int):
    user, error = auth_check()
    if error:
        return error

    session = Session.query.filter_by(id=id).first()

    # If bad session
    if not session or session.archived is True:
        return redirect(url_for('student.unavailability'))

    # If student assigned
    if user.id in [f.user.id for f in session.assignments if not f.removed]:
        return error_render("Currently assigned to session",
                            "You cannot update your unavailability on a session you are currently assigned to."
                            "\nPlease seek help from a staff user to un-assign you from the session")

    # Form
    form = UnavailabilityForm(request.form)

    # Verify the form
    if form.validate_on_submit():

        dbsession = db_session()

        if not form.unavailable.data:
            Unavailability.query.with_session(dbsession).filter_by(user_id=user.id, session_id=session.id).delete()

            dbsession.commit()
            return redirect(url_for('student.unavailability'))

        if form.unavailable.data and form.reason.data:
            Unavailability.query.with_session(dbsession).filter_by(user_id=user.id, session_id=session.id).delete()

            new_unavailablity = Unavailability(user.id, session.id, form.reason.data)
            dbsession.add(new_unavailablity)

            dbsession.commit()
            return redirect(url_for('student.unavailability'))

        flash('Please enter a reason for marking yourself as unavailable')

    # Get current if any
    data = Unavailability.query.filter_by(user_id=user.id, session_id=session.id).first()
    if data:
        form.unavailable.data = True
        form.reason.data = data.reason

    # Render
    return render_template("student/unavailability_edit.jinja2", form=form)


# Sign in
@student.route('/attendance/in/', methods=['GET'])
def attendance_in():

slst-rota/app/templates/student/index.jinja2
{% extends "app/base.jinja2" %}

{% block title %}Student Portal{% endblock %}

{% block body %}
    {% set this_user = auth.current_user() %}
    <div class="container">
        <div class="row">
            <div class="two-thirds column">
                <h1 class="mt-4">
                    Hello {{ this_user.username }}
                </h1>

                {% if next_session %}
                    {% set current_next = "<b>current</b>" if session_is_current else "next" %}
                    <h4 class="mb-0">
                        Your {{ current_next }} rota assignment
                    </h4>
                    {% from "app/macros/table.jinja2" import render_table with context %}
                    {{ render_table(["Day", "Start Time", "End Time", "Student(s) Assigned"], [next_session]) }}
                {% else %}
                    <h4>No sessions assigned to your user</h4>
                {% endif %}
                <a href="{{ url_for("student.rota") }}" class="button primary mt-1">
                    <i class="fas fa-lg fa-calendar-day"></i> View personal rota
                </a>
                <a href="{{ url_for("student.rota_full") }}" class="button mt-1">
                    <i class="fas fa-lg fa-calendar-alt"></i> View full rota
                </a>
            </div>
            <div class="one-third column">
                {% if next_session and (session_is_current or session_is_soon) %}
                    {% if not signed_in_out_session[1] %}
                        <h4 class="mt-4 mb-0">Not signed in for {{ current_next }} assignment</h4>
                        <a href="{{ url_for("student.attendance_in") }}" class="button success mt-1">Sign in for
                            {{ current_next }} assignment</a>
                    {% elif not signed_in_out_session[2] %}
                        <h4 class="mt-4 mb-0">Signed in for {{ current_next }} assignment</h4>
                        <a href="{{ url_for("student.attendance_out") }}" class="button danger mt-1">Sign out
                            from {{ current_next }} assignment</a>
                    {% else %}
                        <h4 class="mt-4 mb-0">Already signed out from {{ current_next }} assignment</h4>
                    {% endif %}
                {% else %}
                    <h4 class="mt-4 mb-0">No current assignment</h4>
                {% endif %}
                <hr/>

                <h4 class="mt-4 mb-0">Your session unavailability</h4>
                <div class="row">
                    <p>
                        {{ unavailability_stat }}<br/>
                        <a href="{{ url_for("student.unavailability") }}" class="button mt-1">
                            <i class="fas fa-comment-alt"></i> Manage unavailability
                        </a>
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

slst-rota/app/templates/student/rota.jinja2
{% extends "app/base.jinja2" %}

{% block title %}Student Rota{% endblock %}

{% block body %}
    {% set this_user = auth.current_user() %}
    <div class="container">
        <div class="row">
            <h1 class="mt-4">
                {{ title }}
            </h1>
            {% from "app/macros/table.jinja2" import render_table with context %}
            {{ render_table(["Start Time", "End Time", "Student(s) Assigned"], rota_data) }}
            {% if show_rota_full %}
                {% if has_highlighted %}
                    <p>Sessions highlighted are for today.</p>
                {% endif %}
                <a class="button primary mt-2" href="{{ url_for('student.rota_full') }}">
                    <i class="fas fa-lg fa-calendar-alt"></i> View full rota
                </a>
            {% else %}
                {% if has_highlighted %}
                    <p>Sessions highlighted are assigned to you.</p>
                {% endif %}
                <a class="button primary mt-2" href="{{ url_for('student.rota') }}">
                    <i class="fas fa-lg fa-calendar-day"></i> View personal rota
                </a>
            {% endif %}
        </div>
    </div>
{% endblock %}

slst-rota/app/templates/student/unavailability.jinja2
{% extends "app/base.jinja2" %}

{% block title %}Student Unavailability{% endblock %}

{% block body %}
    {% set this_user = auth.current_user() %}
    <div class="container">
        <div class="row">
            <h1 class="mt-4">
                Unavailability for {{ this_user.username }}
            </h1>
            {% from "app/macros/table.jinja2" import render_table with context %}
            {{ render_table(["Start Time", "End Time", "Unavailable", ""], rota_data) }}
        </div>
    </div>
{% endblock %}

slst-rota/app/templates/student/unavailability_edit.jinja2
{% extends "app/base.jinja2" %}

{% block title %}Student Unavailability{% endblock %}

{% block body %}
    {% from "app/macros/field.jinja2" import render_field with context %}

    <div class="container">
        <h1></h1>
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <div class="message-block">
                    {% for message in messages %}
                        {{ message }}<br>
                    {% endfor %}
                </div>
            {% endif %}
        {% endwith %}

        <form method="POST" action="{{ request.url }}" accept-charset="UTF-8" role="form">
            {{ form.csrf_token }}

            <div class="row">
                <div class="two-thirds column">
                    {{ render_field(form.unavailable, placeholder="Unavailable", autofocus="") }}
                    {{ render_field(form.reason, placeholder="Reason") }}
                </div>
                <div class="one-third column">
                    <button type="submit" name="submit" class="button primary mt-4">
                        <span class="fa-stack fa-1x">
                            <i class="fas fa-check fa-stack-1x"></i>
                            <i class="far fa-comment-alt fa-stack-2x"></i>
                        </span>
                        Update
                    </button>
                    <br/>
                    <a role="button" href="{{ url_for("student.unavailability") }}" class="button mt-4">
                        <i class="fas fa-lg fa-arrow-left"></i>
                        Cancel
                    </a>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

{% block extra_js %}
    <script src="/static/js/checkboxes.js"></script>
{% endblock extra_js %}