slst-rota/app/m_auth/controllers.py
from flask import Blueprint, request, render_template, flash, session, redirect, url_for  # Flask
from werkzeug.security import check_password_hash  # Passwords

from app.m_auth.forms import LoginForm  # Forms
from app.m_auth.models import User  # Models

# Blueprint
m_auth = Blueprint('auth', __name__, url_prefix='/auth')


# Set the route and accepted methods
@m_auth.route('/login/', methods=['GET', 'POST'])
def login():
    # If sign in form is submitted
    form = LoginForm(request.form)

    # Verify the sign in form
    if form.validate_on_submit():

        user = User.query.filter_by(username=form.username.data).first()

        if user and check_password_hash(user.password, form.password.data):
            session['user_id'] = user.id

            flash('Welcome %s' % user.name)

            return redirect(url_for('auth.home'))

        flash('Wrong email or password', 'error-message')

    return render_template("auth/login.jinja2", form=form)

slst-rota/app/templates/index.jinja2
{% extends "app/base.jinja2" %}

{% block title %}Welcome{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="media mt-4">
                <div class="left">
                    <h1><i class="fas fa-calendar-alt"></i></h1>
                </div>
                <div class="main">
                    <h1>{{ app.name }} - Welcome</h1>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="two-thirds column">
                <ul>
                    <li>Provide an easy to use rota system for students on duty in the precinct</li>
                    <li>Provide an easy management system of the rota system for staff</li>
                </ul>
                <ul>
                    <li>Allow students to indicate days they cannot complete precinct duty</li>
                    <li>Allow students to sign in and out of their current precinct duty and for this to be tracked</li>
                    <li>Display an easy to understand timetable of duties for the precinct</li>
                </ul>
                <ul>
                    <li>Allow staff to define the precinct duty sessions for the week</li>
                    <li>Allow staff to view when students signed in and out</li>
                    <li>Allow staff to view in-depth analytics regarding student attendance for their duties</li>
                    <li>
                        Display to staff the attendance levels for individual students on the precinct, the student’s
                        reliability
                    </li>
                    <li>
                        Display to staff the duration each student stays for their precinct duty, percentage of defined
                        precinct duration
                    </li>
                </ul>
                <ul>
                    <li>Provide an authentication system for staff and students</li>
                    <li>Allow staff to easily manage student accounts and other staff accounts</li>
                </ul>
            </div>
            <div class="one-third column">
                <a href="{{ url_for('auth.login') }}" class="button larger primary mt-1">
                    <i class="fas fa-lg fa-sign-in-alt"></i> Sign in to get started
                </a>
            </div>
        </div>
    </div>
{% endblock %}