slst-rota/app/m_auth/controllers.py
from flask import Blueprint, request, render_template, flash, session, redirect, url_for  # Flask
from werkzeug.security import check_password_hash  # Passwords

from app.m_auth.forms import LoginForm  # Forms
from app.m_auth.models import User  # Models

# Blueprint
m_auth = Blueprint('auth', __name__, url_prefix='/auth')


# Set the route and accepted methods
@m_auth.route('/login/', methods=['GET', 'POST'])
def login():
    # If sign in form is submitted
    form = LoginForm(request.form)

    # Verify the sign in form
    if form.validate_on_submit():

        user = User.query.filter_by(username=form.username.data).first()

        if user and check_password_hash(user.password, form.password.data):
            session['user_id'] = user.id

            flash('Welcome %s' % user.name)

            return redirect(url_for('auth.home'))

        flash('Wrong email or password', 'error-message')

    return render_template("auth/login.jinja2", form=form)

slst-rota/app/modules/staff/controllers.py
import calendar  # Calendar
import json  # JSON
from datetime import datetime  # Datetime
from typing import List, Union, Dict, Tuple  # Typing

from flask import Blueprint, render_template, redirect, url_for, request, flash  # Flask
from werkzeug.security import generate_password_hash  # Passwords

from app import db_session, error_render, Utils  # DB, Errors, Utils
from app.modules import auth  # Auth
from app.modules.auth import User  # User
from app.modules.staff.forms import AccountForm, SessionForm, SessionDeleteForm, \
    AssignmentForm, AutomaticAssignmentForm  # Forms
from app.modules.student import Session, Assignment, Unavailability  # Session

# Blueprint
__a = [

]  # Convince pycharm things are used (and stop warnings)
staff = Blueprint('staff', __name__, url_prefix='/staff')


# Standard check for all routes
def auth_check():
    user = auth.current_user()
    error = None

    # If no session exists
    if not error and not user:
        error = redirect(url_for('auth.login'))

    # If not staff
    if not error and user.auth_level != 2:
        error = error_render("Staff access only",
                             "This page is only accessible to users with the staff authentication level")

    return user, error


# Fetch the next user in the rotation that is assignable
def next_assignable(total_assigned: Dict[int, list], assigned: List[User], session: Session,
                    force_next: bool = False) -> Union[None, User]:
    # The user that hopefully will be found
    next_user = None

    # Order users by assignments so far (smallest first)
    users_sorted = sorted(total_assigned.values(), key=lambda x: (x[0], x[1].username.lower()))

    # Loop over users until we find one (least assignments first)
    for user in users_sorted:
        # Get the user object
        user_obj = user[1]  # [int (assignments), user]

        # Check if already assigned
        if user_obj in assigned:
            continue

        # Check if available
        unavailable = Unavailability.query.filter_by(session_id=session.id, user_id=user_obj.id).all()
        if unavailable:
            continue

        # Store
        next_user = user
        break

    # If all unavailable and want to force, select first
    if force_next and next_user is None:
        users_sorted = [f for f in users_sorted if f[1] not in assigned]
        if users_sorted:
            next_user = users_sorted[0]

    # If have user, update assinged
    if next_user is not None:
        next_user = next_user[1]
        assigned.append(next_user)
        total_assigned[next_user.id][0] += 1

    # Done
    return next_user


# Generate assignments
def generate_assignments(users_per_session: int = 1, force_user: bool = True):
    # Fetch all sessions
    sessions = Session.query.filter_by(archived=False).all()
    if not sessions:
        return

    # Fetch all users
    users = User.query.filter_by(auth_level=1, disabled=False).all()
    if not users:
        return

    # DB
    dbsession = db_session()

    # Remove old assignments
    assignments = Assignment.query.with_session(dbsession).filter_by(removed=None).all()
    for assignment in assignments:
        assignment.removed = datetime.now()
    dbsession.commit()

    # Loop over sessions
    total_assigned = {f.id: [0, f] for f in users}
    for session in sessions:
        # Correct number of users per session
        target = users_per_session
        assigned = []

        # Loop for target
        while target > 0:

            # Get next user to assign (will also update both assigned)
            student = next_assignable(total_assigned, assigned, session, force_user)

            # Give up if no users
            if not student:
                break

            # Update target
            target -= 1
            # Assign
            assignment = Assignment(student.id, session.id)
            dbsession.add(assignment)
            dbsession.commit()


# Check if a new session overlaps an existing one
def check_session_overlap(session) -> Tuple[bool, Union[Session, None]]:
    sessions = Session.query.filter_by(day=session.day).order_by(Session.day.asc(), Session.start_time.asc()).all()
    for sess in sessions:
        # Skip current
        if session.id == sess.id:
            continue
        # Check start overlap
        if sess.start_time < session.start_time < sess.end_time:
            return False, sess
        # Check end overlap
        if sess.start_time < session.end_time < sess.end_time:
            return False, sess
        # Check in between
        if sess.start_time > session.start_time and sess.end_time < session.end_time:
            return False, sess
    return True, None


# All accounts
@staff.route('/accounts/', methods=['GET'])
def accounts():
    user, error = auth_check()
    if error:
        return error

    data = User.query.all()
    all_accounts = []
    for item in data:
        all_accounts.append([
            item.id == user.id,
            [
                [item.username] * 2,
                [item.auth_label, item.auth_level],
                ["Yes" if item.disabled == 1 else "No", int(item.disabled != 1)],
                "<a href='{}' class='button'><i class=\"fas fa-lg fa-user-edit\"></i> Edit</a>".format(
                    url_for("auth.account", id=item.id))
            ]
        ])

    return render_template("staff/accounts.jinja2", accounts=all_accounts)


# Create Account
@staff.route('/accounts/new', methods=['GET', 'POST'])
def new_account():
    user, error = auth_check()
    if error:
        return error

    # Form
    form = AccountForm(request.form)

    # Verify the form
    if form.validate_on_submit():

        # Verify username
        if form.username.data:

            result = User.query.filter_by(username=form.username.data).first()

            # Verify username not already used
            if not result:

                # Verify password
                if form.password.data:

                    # Verify auth level
                    if form.auth_level.data:

                        session = db_session()
                        user = User(form.username.data, generate_password_hash(form.password.data),
                                    form.auth_level.data)
                        session.add(user)
                        session.commit()
                        return redirect(url_for('staff.accounts'))

                    else:
                        flash('Please select an auth level')

                else:
                    flash('Please enter a password')

            else:
                flash('Username {} already in use'.format(form.username.data))

        else:
            flash('Please enter a username')

    # Render
    return render_template("staff/new_account.jinja2", form=form)


# Rota view
@staff.route('/rota/', methods=['GET'])
def rota():
    user, error = auth_check()
    if error:
        return error

    # Get rota data
    data = Session.query.filter_by(archived=False).order_by(Session.day.asc(), Session.start_time.asc()).all()
    rota_data = []
    current_day = None
    for session in data:
        # Day subheadings
        if session.day != current_day:
            rota_data.append([False, [list(calendar.day_name)[session.day], "", "", ""], True])
            current_day = session.day

        # Assignments for day (highlight ones with current user)
        rota_data.append([
            ([f for f in session.assignments if not f.removed] == []),
            [
                session.start_time_frmt,
                session.end_time_frmt,
                ", ".join(
                    [f.user.username for f in session.assignments if not f.removed and not f.user.disabled]) or "None",
                "<a href='{}' class='button'><i class=\"fas fa-lg fa-edit\"></i> Edit Session</a>"
                "".format(url_for("staff.rota_edit_session", id=session.id)) +
                " &nbsp; <a href='{}' class='button'><i class=\"fas fa-lg fa-users-cog\"></i> Update Assignments</a>"
                "".format(url_for("staff.rota_edit_assignments", id=session.id))
            ]
        ])

    return render_template("staff/rota.jinja2", rota_data=rota_data)


# Rota edit - session
@staff.route('/rota/edit/session/<int:id>', methods=['GET', 'POST'])
def rota_edit_session(id: int):
    user, error = auth_check()
    if error:
        return error

    # Get session data
    session = Session.query.filter_by(archived=False, id=id).first()

    # If bad session
    if not session:
        return redirect(url_for('staff.rota'))

    # Form
    form = SessionForm(request.form)

    # Verify the form
    if form.validate_on_submit():

        # Verify day
        if form.day.data is not None and type(form.day.data) is int and -1 < form.day.data < len(calendar.day_name):

            # Verify start time
            if form.start_time.data is not None:

                # Verify end time
                if form.end_time.data is not None:

                    # Verify times
                    if form.start_time.data < form.end_time.data:

                        dbsession = db_session()
                        session = Session.query.with_session(dbsession).filter_by(id=id).first()

                        start_time = datetime.combine(datetime.now().date(), form.start_time.data)
                        start_time = int(Utils.minutes_datetime(start_time))

                        end_time = datetime.combine(datetime.now().date(), form.end_time.data)
                        end_time = int(Utils.minutes_datetime(end_time))

                        session.day = form.day.data
                        session.start_time = start_time
                        session.end_time = end_time

                        check = check_session_overlap(session)
                        if check[0]:
                            dbsession.commit()

slst-rota/app/templates/app/base.jinja2
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>

    <!-- General -->
    <title>{% block title %}{% endblock %} - {{ app.name }}</title>
    <link rel="shortcut icon" href=""/>
    <link rel="icon" type="image/png" href=""/>
    <meta name="title" content="{{ app.name }} - {{ self.title() }}"/>
    <meta name="description" content="{{ app.name }} - {{ self.title() }} - {{ app.description }}"/>
    <link href="/static/css/main.css" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,600" rel="stylesheet"/>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
          integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous"/>

    <!-- Social -->
    <!-- Social: Twitter -->
    <meta name="twitter:card" content="summary"/>
    <meta name="twitter:title" content="{{ app.name }} - {{ self.title() }}"/>
    <meta name="twitter:description" content="{{ app.name }} - {{ self.title() }} - {{ app.description }}"/>
    <meta name="twitter:image" content=""/>
    <meta name="twitter:url" content="{{ request.url_route }}"/>
    <!-- Social: OpenGraph -->
    <meta prefix="og: http://ogp.me/ns#" property="og:title" content="{{ app.name }} - {{ self.title() }}"/>
    <meta prefix="og: http://ogp.me/ns#" property="og:type" content="website"/>
    <meta prefix="og: http://ogp.me/ns#" property="og:locale" content="en_GB"/>
    <meta prefix="og: http://ogp.me/ns#" property="og:site_name" content="{{ app.name }}"/>
    <meta prefix="og: http://ogp.me/ns#" property="og:description"
          content="{{ app.name }} - {{ self.title() }} - {{ app.description }}"/>
    <meta prefix="og: http://ogp.me/ns#" property="og:url" content="{{ request.url_route }}"/>
    <meta prefix="og: http://ogp.me/ns#" property="og:image" content=""/>
    <meta prefix="og: http://ogp.me/ns#" property="og:image:url" content=""/>

    <!-- Web app -->
    <meta name="apple-mobile-web-app-capable" content="yes"/>
    <meta name="apple-mobile-web-app-status-bar-style" content="black"/>
    <meta name="format-detection" content="telephone=no"/>
    <link rel="apple-touch-icon" href=""/>
    <meta name="apple-mobile-web-app-title" content="{{ app.name }}"/>
    <meta name="theme-color" content=""/>

    {% block extra_head %}{% endblock %}
</head>
<body>

{% include 'app/navbar.jinja2' %}

{% block body %}{% endblock %}

{% include 'app/footer.jinja2' %}

{% block extra_js %}{% endblock %}

</body>
</html>

slst-rota/app/templates/app/error.jinja2
{% extends "app/base.jinja2" %}

{% block title %}Error - {{ error_message }}{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">

            <div class="media">
                <div class="left">
                    <h1><i class="fas fa-exclamation-triangle"></i></h1>
                </div>
                <div class="main">
                    <h2>
                        Sadly we've encountered an error... {{ error_message }}
                        <br/>
                        <small>{{ error_details }}</small>
                        <br/>
                        <small>{{ error_extra }}</small>
                    </h2>
                </div>
            </div>

            <a class="button primary mt-2" href="{{ url_for('index') }}">Head to Safety - Home</a>
        </div>
    </div>
{% endblock %}

slst-rota/app/templates/app/footer.jinja2
<footer class="footer">
    <div class="container">
        <div class="row">
            <p>
                <i class="far fa-copyright"></i> {{ datetime.now().year }}
                <a href="https://mattcowley.co.uk" target="_blank">Matt Cowley</a>.
                All Rights Reserved.
                <br/>
                <span class="small-text">
                    Icons provided by <a href="http://fontawesome.io" target="_blank">FontAwesome</a>.
                    CSS framework by <a href="http://getskeleton.com/" target="_blank">Skeleton CSS</a>.
                </span>
            </p>
        </div>
    </div>
</footer>

slst-rota/app/templates/app/navbar.jinja2
<header class="navbar">
    <div class="container larger">
        <div class="row">
            {% set this_user = auth.current_user() %}
            <a class="item title" href="{{ url_for('index') }}">
                {{ app.name }}
            </a>

            <a class="item" href="{{ url_for('index') }}">
                <i class="fas fa-igloo"></i> Home
            </a>

            {% if this_user and this_user.auth_level == 1 %}
                {# Student #}
                <span class="dropdown">
                    <a class="droptitle" href="{{ url_for('student.rota') }}">
                        <i class="fas fa-calendar-alt"></i> Rota <i class="fas fa-angle-right"></i>
                    </a>
                    <span class="drop">
                        <a class="item" href="{{ url_for('student.rota') }}">Personal Rota</a>
                        <a class="item" href="{{ url_for('student.rota_full') }}">Full Rota</a>
                    </span>
                </span>

                <a class="item" href="{{ url_for('student.unavailability') }}">
                    <i class="fas fa-comment-alt"></i> Unavailability
                </a>
                <a class="item" href="{{ url_for('attendance.student', student_id=this_user.id) }}">
                    <i class="fas fa-clipboard-list"></i> Attendance
                </a>
            {% elif this_user and this_user.auth_level == 2 %}
                {# Staff #}
                <span class="dropdown">
                    <a class="droptitle" href="{{ url_for('staff.accounts') }}">
                        <i class="fas fa-users"></i> Accounts <i class="fas fa-angle-right"></i>
                    </a>
                    <span class="drop">
                        <a class="item" href="{{ url_for('staff.accounts') }}">All Accounts</a>
                        <a class="item" href="{{ url_for('staff.new_account') }}">New Account</a>
                    </span>
                </span>

                <span class="dropdown">
                    <a class="droptitle" href="{{ url_for('staff.rota') }}">
                        <i class="fas fa-calendar-alt"></i> Rota Management <i class="fas fa-angle-right"></i>
                    </a>
                    <span class="drop">
                        <a class="item" href="{{ url_for('staff.rota') }}">Full Student Rota</a>
                        <a class="item" href="{{ url_for('staff.rota_new') }}">New Rota Session</a>
                    </span>
                </span>

                <a class="item" href="{{ url_for('attendance.home') }}">
                    <i class="fas fa-clipboard-list"></i> Attendance
                </a>
            {% endif %}

            <span class="right">
                {% if this_user %}
                    <span class="dropdown">
                        <a class="droptitle" href="{{ url_for('auth.account') }}">
                            <i class="fas fa-user"></i> {{ this_user.username }}
                            {{ this_user.auth_label }} <i class="fas fa-angle-right"></i>
                        </a>
                        <span class="drop">
                            <a class="item" href="{{ url_for('auth.account') }}">Account</a>
                            <a class="item" href="{{ url_for('auth.logout') }}">Logout</a>
                        </span>
                    </span>
                {% else %}
                    <a class="item" href="{{ url_for('auth.login') }}">
                        <i class="fas fa-sign-in-alt"></i> Login
                    </a>
                {% endif %}
            </span>
        </div>
    </div>
</header>